// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-n8-pfRwiHRniSJzKzeKkhqV0VZR2sk',
    appId: '1:233668605461:web:9aaf74c273dd601f0a001c',
    messagingSenderId: '233668605461',
    projectId: 'chat-app-8f20a',
    authDomain: 'chat-app-8f20a.firebaseapp.com',
    storageBucket: 'chat-app-8f20a.firebasestorage.app',
    measurementId: 'G-E9LF4LXY0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwuVFswLWlOR4hpkX_ChUjKocqhq0ILzU',
    appId: '1:233668605461:android:23863af4d97774750a001c',
    messagingSenderId: '233668605461',
    projectId: 'chat-app-8f20a',
    storageBucket: 'chat-app-8f20a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfLmKMRzLSl-CxqRxmHO0rMlmyJpo46I',
    appId: '1:233668605461:ios:75cdcb2bd5c77cde0a001c',
    messagingSenderId: '233668605461',
    projectId: 'chat-app-8f20a',
    storageBucket: 'chat-app-8f20a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdfLmKMRzLSl-CxqRxmHO0rMlmyJpo46I',
    appId: '1:233668605461:ios:75cdcb2bd5c77cde0a001c',
    messagingSenderId: '233668605461',
    projectId: 'chat-app-8f20a',
    storageBucket: 'chat-app-8f20a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0-n8-pfRwiHRniSJzKzeKkhqV0VZR2sk',
    appId: '1:233668605461:web:5534c94943df02db0a001c',
    messagingSenderId: '233668605461',
    projectId: 'chat-app-8f20a',
    authDomain: 'chat-app-8f20a.firebaseapp.com',
    storageBucket: 'chat-app-8f20a.firebasestorage.app',
    measurementId: 'G-GJ3H9T6759',
  );
}
